name: Unit tests

on:
  push:
    branches:
      - 3.x.x-dev
  pull_request:
    branches:
      - 3.x.x-dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0', '9.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v3

      - name: Check .NET SDKs Installed
        run: dotnet --list-sdks

      - name: Install dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test smsapiTests/smsapiTests.csproj --configuration Release --no-build --verbosity normal --framework net${{ matrix.dotnet-version }}
